SUBSAMPLING_SIZE = 60
DATA_SIZE = 60*60*24*30*2 # start from 2 months ago
INPUT_SIZE = 60*60*3   # 3 hours
SHIFT_SIZE = 60  # 1 minute
INPUT_SIZE //= SUBSAMPLING_SIZE
SHIFT_SIZE //= SUBSAMPLING_SIZE

OUTPUT_SIZE = 1
TEST_DATASET_SIZE = 8
SHUFFLE_BUFFER_SIZE = 100
BATCH_SIZE = 64
EPOCHS = 10

PREDICTION_SIZE = 60*30 # 30 minutes
PREDICTION_SIZE //= SUBSAMPLING_SIZE
SHOW_DIFFERENCE = True