# needed by preprocess.py
SUBSAMPLING_SIZE = 60
INPUT_SIZE = 60*60*3 // SUBSAMPLING_SIZE  # 3 hours
SHIFT_SIZE = 60*20 // SUBSAMPLING_SIZE  # 1/3 hour

OUTPUT_SIZE = 1  # 60*60*8 // SUBSAMPLING_SIZE  # 1/3 day
TEST_DATASET_SIZE = 8
SHUFFLE_BUFFER_SIZE = 100
BATCH_SIZE = 64
PREDICTION_SIZE = 60
SHOW_DIFFERENCE = False